#!/usr/bin/env python3
"""Generate every sub-page on the site using the 4-block universal template:
hero banner image → 1 paragraph copy → 1 column of stacked photos → CTA w/ banner.

Run from homepage/ root. Writes 19 HTML files.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HOME = ROOT


# ────────────────────────────────────────────────────────────────────────────
# Page data
# ────────────────────────────────────────────────────────────────────────────
# Per-page fields:
#   out:          output path relative to homepage/
#   prefix:       relative URL prefix used in nav (e.g., "../" for one-level-deep)
#   title, desc, canonical
#   crumbs:       list of (label, href) tuples for breadcrumb; last has href=None
#   hero_img:     hero banner image path (relative to page)
#   eyebrow, h1:  hero overlay text (h1 supports <em>)
#   copy_eye, copy_h2, copy_p:  copy block
#   photos:       list of (src, caption) tuples
#   cta_eye, cta_h2, cta_p, cta_btn_text, cta_btn_href, cta_bg
#   schema:       optional schema.org JSON-LD (string, full <script> block) or None

PAGES = []


def add(**kwargs):
    PAGES.append(kwargs)


# ─── HOMEPAGE ────────────────────────────────────────────────────────────────
# (Homepage is NOT regenerated by this script; it's bespoke.)

# ─── ABOUT ───────────────────────────────────────────────────────────────────

add(
    out="about/index.html",
    prefix="../",
    title="About · Radius Architectural Millwork · Burnaby BC",
    desc="A Master Joiner-led custom millwork shop in Burnaby, BC. Same shop, same bench, same Government Street address since 2002. AWMAC Gold 2011.",
    canonical="https://radiuswood.com/about/",
    crumbs=[("Home", "../"), ("About", None)],
    hero_img="../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-living-room-atrium-garden-walnut-slat-ceiling.jpg",
    eyebrow="About",
    h1="Twenty-five years on the <em>same bench.</em>",
    copy_eye="The Shop",
    copy_h2="A Master Joiner-led custom millwork shop in Burnaby.",
    copy_p="Founded by <strong>Rick Wilson</strong> in 2002 — BCIT-trained Master Joiner with a decade at Wilms before he opened the bench on Government Street. Today the floor runs twenty craftspeople: cabinetmakers, finishers, installers, all employees, all in-house. AWMAC BC Gold in 2011 with Lamoureux Architects. Five consecutive years of Best of Houzz. Selected by Shift Interiors. Featured inside the Bjarke Ingels Vancouver House. <strong>Same shop, same bench, same address since the day we opened.</strong>",
    photos=[
        ("../photos/indian-arm-study/indian-arm-woodlands-study-living-room-wide-stone-wall.jpg", "Indian Arm Study · cedar + stone"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-diamond-bookmatched-ceiling-up-view-fireplace-anigre-pantry.jpg", "Waterfront Anigre · diamond bookmatched ceiling"),
        ("../photos/indian-river-the-point/indian-river-the-point-living-room-gable-end-harbor-view-bocci-pendants-media-wall.jpg", "Indian River · The Point · gable-end living"),
        ("../photos/contemporary-walnut-estate/contemporary-walnut-estate-wine-cellar-walnut-rack-perspective.jpg", "Contemporary Walnut Estate · wine cellar"),
    ],
    cta_eye="Get in touch",
    cta_h2="Have a project on the boards? <em>Send us the set.</em>",
    cta_p="Drawings, scope, timeline, or just a conversation. We respond within two business days with a feasibility read and a tested quote.",
    cta_btn_text="Request a Quote",
    cta_btn_href="../contact.html",
    cta_bg="../projects/cta-vancouverhouse-living-dining.jpg",
)

add(
    out="about/company.html",
    prefix="../",
    title="The Company · About · Radius Architectural Millwork",
    desc="Rick Wilson founded Radius in 2002 after a decade at Wilms Millwork. BCIT-trained Master Joiner. Twenty craftspeople, five thousand square feet on Government Street, twenty-five years on the same bench.",
    canonical="https://radiuswood.com/about/company/",
    crumbs=[("Home", "../"), ("About", "./"), ("Company", None)],
    hero_img="../photos/indian-arm-study/indian-arm-woodlands-study-living-room-wide-stone-wall.jpg",
    eyebrow="About · Company",
    h1="One shop. <em>One bench. One address.</em>",
    copy_eye="Origin",
    copy_h2="Rick started Radius in 2002.",
    copy_p="BCIT for joinery. A decade on the bench at <strong>Wilms Millwork</strong>. The Government Street shop opened in 2002 with three people and a long-radius bending form for a single curved alder rotunda — the curve held, the shop grew around the bench. Today the floor runs twenty craftspeople, all in-house, all employees: journeymen, finishers, installers. <strong>Concept to completion under one roof, twenty-five years on the same address.</strong> AWMAC BC Gold in 2011 with Lamoureux Architects. AWMAC 2027 submission currently on the bench — Old Gravel Road, Whistler, forty-three sheets of rift-and-smoked-oak millwork.",
    photos=[
        ("../photos/contemporary-walnut-estate/contemporary-walnut-estate-walnut-fireplace-wall-detail.jpg", "Walnut fireplace wall · Contemporary Walnut Estate"),
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-mantel-carved-corbel-close-up.jpg", "Hand-carved corbel · Maghsoud Residence"),
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-walnut-slat-door-black-handle-detail.jpg", "Walnut slat door detail · Vancouverhouse"),
        ("../photos/lions-bay/lions-bay-residence-painted-corbel-carved-detail.jpg", "Painted carved corbel · Lion's Bay"),
    ],
    cta_eye="Visit the shop",
    cta_h2="Want to see the bench? <em>Drop us a line.</em>",
    cta_p="Site walks at the shop by appointment — Friday afternoons usually work best. Bring drawings, bring questions; we'll show you the press, the spray booth, and the project on it.",
    cta_btn_text="Get in Touch",
    cta_btn_href="../contact.html",
    cta_bg="../photos/indian-arm-study/indian-arm-woodlands-study-living-room-wide-cedar-ceiling.jpg",
)

add(
    out="about/our-vision.html",
    prefix="../",
    title="Our Vision · About · Radius Architectural Millwork",
    desc="Master Joiner-led. Zero CNC. Slip-matched veneer, hand-cut joinery, bent lamination — engineered into every piece. The principles we hold the work to.",
    canonical="https://radiuswood.com/about/our-vision/",
    crumbs=[("Home", "../"), ("About", "./"), ("Our Vision", None)],
    hero_img="../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-diamond-bookmatched-ceiling-up-view-fireplace-anigre-pantry.jpg",
    eyebrow="About · Our Vision",
    h1="Master Joiner-led. <em>Hand-cut. Slip-matched.</em>",
    copy_eye="The Vision",
    copy_h2="Quality and sophistication, <em>continuously evolving.</em>",
    copy_p="To create an emotional experience and unique environments within the home — through physical form and texture in wood. <strong>Zero CNC, by choice.</strong> All cuts, all joinery, all assembly are bench work. The figure of the wood runs the room: veneer slip-matched and sequenced in the order it came off the log; every door, every panel from the same flitch. Joinery is engineered into the work where the eye won't see it but the hand will — pin-and-tail dovetails, mortise-and-tenon, bent lamination over custom jigs. The standard is the same for every project: <strong>built to last generations, not seasons.</strong>",
    photos=[
        ("../photos/indian-river-the-point/indian-river-the-point-white-oak-stair-tongue-and-groove.jpg", "Tongue-and-groove rift oak stair · Indian River"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-diamond-bookmatched-ceiling-up-view-fireplace-anigre-pantry.jpg", "Diamond-bookmatched anigre · Waterfront"),
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-master-bath-freestanding-tub-curved-walnut-slat-wall.jpg", "Curved walnut slat wall · Vancouverhouse"),
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-cherry-panel-wall-bookmatched-detail.jpg", "Bookmatched cherry detail · Whitby Estates"),
    ],
    cta_eye="See the work",
    cta_h2="The vocabulary in built form. <em>Selected projects.</em>",
    cta_p="Selected residential estate work from across British Columbia — slip-matched walnut, diamond-bookmatched anigre, bent-laminated alder, tongue-and-groove rift oak.",
    cta_btn_text="View Our Work",
    cta_btn_href="../work/",
    cta_bg="../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-living-dining-diamond-ceiling-wide-fireplace-wine-bar-dusk.jpg",
)

add(
    out="about/partners.html",
    prefix="../",
    title="Partners · About · Radius Architectural Millwork",
    desc="Selected architects, designers, and photographers we collaborate with. Lamoureux Architects, Shift Interiors, inside the Bjarke Ingels Vancouver House. Photography by Andrew Latreille, Kent Leckie, Hempenstall, Conrad Brown.",
    canonical="https://radiuswood.com/about/partners/",
    crumbs=[("Home", "../"), ("About", "./"), ("Partners", None)],
    hero_img="../photos/indian-river-the-point/indian-river-the-point-living-room-gable-end-harbor-view-bocci-pendants-media-wall.jpg",
    eyebrow="About · Partners",
    h1="Architects, designers, <em>photographers.</em>",
    copy_eye="How we work",
    copy_h2="From the architect's drawing set <em>to the punch-list.</em>",
    copy_p="Most projects come in through architects and interior designers we've worked with before. We slot in at the drawing-review stage — early enough to flag dimensional issues in the millwork run, late enough that the design intent is locked. Selected collaborations include <strong>Lamoureux Architects</strong> (AWMAC BC Gold 2011 — Rosebery Estate), <strong>Shift Interiors</strong> (Indian River — The Point), and a penthouse inside <strong>Bjarke Ingels Group's Vancouver House</strong>. Photography across the portfolio by <strong>Andrew Latreille</strong> (LAP), <strong>Kent Leckie</strong>, <strong>Hempenstall</strong>, and <strong>Conrad Brown</strong>.",
    photos=[
        ("../photos/indian-river-the-point/indian-river-the-point-living-room-gable-end-harbor-view-bocci-pendants-media-wall.jpg", "Indian River — The Point · with Shift Interiors"),
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-bocci-stairwell-dusk-exterior-view.jpg", "Vancouverhouse BOP · inside BIG's Vancouver House"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-living-dining-diamond-ceiling-wide-fireplace-wine-bar-dusk.jpg", "Waterfront Anigre · Hempenstall photography"),
        ("https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/photos/archive/luxury-41.jpg", "Rosebery Estate · with Lamoureux Architects · AWMAC Gold 2011"),
    ],
    cta_eye="Working on a project?",
    cta_h2="We'd like to see the set. <em>Send drawings.</em>",
    cta_p="Whether you're the architect, the designer, or the homeowner — we respond within two business days with a feasibility read and a tested quote.",
    cta_btn_text="Get in Touch",
    cta_btn_href="../contact.html",
    cta_bg="../projects/cta-vancouverhouse-living-dining.jpg",
)

# ─── SERVICES ────────────────────────────────────────────────────────────────

add(
    out="services/index.html",
    prefix="../",
    title="Services · Radius Architectural Millwork · Burnaby BC",
    desc="Custom architectural millwork, cabinetry, panelling, wine cellars, bent-laminated curved work, and furniture. Concept to install, all in-house. AWMAC Gold 2011.",
    canonical="https://radiuswood.com/services/",
    crumbs=[("Home", "../"), ("Services", None)],
    hero_img="../photos/contemporary-walnut-estate/contemporary-walnut-estate-dining-room-wide-fireplace-wine-wall.jpg",
    eyebrow="Services",
    h1="Custom millwork, <em>concept to install.</em>",
    copy_eye="What we do",
    copy_h2="Six service categories, <em>under one roof.</em>",
    copy_p="Every project is bespoke. <strong>Architectural cabinetry</strong> for kitchens, baths, libraries, and offices. <strong>Wall panelling</strong> through public rooms — slip-matched walnut, rift oak, bookmatched anigre. <strong>Custom furniture</strong> with traditional and contemporary joinery engineered in. <strong>Wine cellars</strong> with vertical-rod racking and integrated lighting. <strong>Bent lamination</strong> for rotundas and structural radii up to twenty-foot runs (the AWMAC Gold service). <strong>In-house finishing</strong> from antique cottage to high-gloss contemporary, never sub-contracted out.",
    photos=[
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-kitchen-walnut-marble-backsplash-island.jpg", "Architectural Millwork · Vancouverhouse kitchen"),
        ("../photos/contemporary-walnut-estate/contemporary-walnut-estate-wine-cellar-walnut-rack-perspective.jpg", "Wine Cellar · Contemporary Walnut Estate"),
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-media-room-wide-coffered-tv-fireplace-built-ins.jpg", "Custom Furniture · Whitby Estates media room"),
        ("../photos/west-vancouver-modern-luxury/west-vancouver-modern-luxury-coffee-bar-ceiling-banded-lights-fireplace-wide.jpg", "Finishing · West Vancouver Modern Luxury"),
    ],
    cta_eye="Get in touch",
    cta_h2="Have a project on the boards? <em>Send us the set.</em>",
    cta_p="Drawings, scope, timeline, or just a conversation. We respond within two business days with a feasibility read and a tested quote.",
    cta_btn_text="Request a Quote",
    cta_btn_href="../contact.html",
    cta_bg="../projects/cta-vancouverhouse-living-dining.jpg",
)

add(
    out="services/architectural-millwork.html",
    prefix="../",
    title="Architectural Millwork · Services · Radius Architectural Millwork",
    desc="Custom architectural millwork, cabinetry, panelling, wine cellars, bent-laminated curved work, and furniture. Slip-matched veneer, hand-cut joinery, in-house finishing.",
    canonical="https://radiuswood.com/services/architectural-millwork/",
    crumbs=[("Home", "../"), ("Services", "./"), ("Architectural Millwork", None)],
    hero_img="../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-kitchen-walnut-marble-backsplash-island.jpg",
    eyebrow="Services · Architectural Millwork",
    h1="The core service. <em>Built at the bench.</em>",
    copy_eye="Overview",
    copy_h2="What architectural millwork <em>covers, in practice.</em>",
    copy_p="Most of what we build falls under this category — <strong>kitchen cabinetry</strong>, <strong>wall panelling</strong>, <strong>master suites</strong>, <strong>wine rooms</strong>, <strong>media rooms</strong>, custom <strong>doors and hardware</strong>. The scope can be a single feature wall or the millwork package for a whole house. Five phases through the shop: concept + drawings (architect's set in, shop-side detailing); drafting + mock-up (3D renders, full-scale mock-ups before the final cut); the bench (slip-matched veneers, hand-cut dovetails, mortise-and-tenon); in-house finishing (conversion varnish to hard-wax oil, six coats, between-coat sanded); install + punch-list (shipped and installed by the team that built it).",
    photos=[
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-living-room-atrium-garden-walnut-slat-ceiling.jpg", "Walnut slat ceiling · Vancouverhouse BOP"),
        ("../photos/indian-river-the-point/indian-river-the-point-kitchen-white-oak-slat-wall-river-rock-fireplace-column.jpg", "Slip-matched rift oak · Indian River"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-gallery-wine-bar-anigre-display-inuit-sculpture.jpg", "Gallery wine bar · Waterfront Anigre"),
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-media-room-corner-wide-built-ins-double-doors.jpg", "Coffered media room · Maghsoud Residence"),
    ],
    cta_eye="Get in touch",
    cta_h2="Have a project on the boards? <em>Send us the set.</em>",
    cta_p="Drawings, scope, timeline, or just a conversation. We respond within two business days with a feasibility read and a tested quote.",
    cta_btn_text="Request a Quote",
    cta_btn_href="../contact.html",
    cta_bg="../projects/cta-vancouverhouse-living-dining.jpg",
)

add(
    out="services/3d-renderings.html",
    prefix="../",
    title="3D Renderings · Services · Radius Architectural Millwork",
    desc="Industry-specific CAD renderings with texture. Full mock-ups of every project before we cut. See your project in real proportions and avoid costly errors on the floor.",
    canonical="https://radiuswood.com/services/3d-renderings/",
    crumbs=[("Home", "../"), ("Services", "./"), ("3D Renderings", None)],
    hero_img="../photos/west-vancouver-modern-luxury/west-vancouver-modern-luxury-curved-stair-concrete-wall-cherry-treads.jpg",
    eyebrow="Services · 3D Renderings",
    h1="See it built, <em>before we cut.</em>",
    copy_eye="Why",
    copy_h2="Catch the issue <em>on the screen, not on the wall.</em>",
    copy_p="3D renderings de-risk a project. Every render incorporates precisely scaled measurements that result in an accurate, real-life digital depiction. <strong>We catch dimensional issues, slip-match transitions, and sub-trade collisions before we cut a single piece of stock.</strong> Created from photos, drawings, designs, or charts — for residential and commercial scopes, interior and exterior. Renders are step two of the build, between concept drawings and the bench. Visit the shop and walk through your project at scale before we commit to final stock.",
    photos=[
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-kitchen-marble-island-wide-walnut-slat-ceiling.jpg", "Vancouverhouse — kitchen mock-up matched to build"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-diamond-bookmatched-ceiling-up-view-fireplace-anigre-pantry.jpg", "Waterfront — diamond ceiling matched to render"),
        ("../photos/indian-river-the-point/indian-river-the-point-kitchen-white-oak-pantry-open-moss-green-island.jpg", "Indian River — moss-green island, render to build"),
    ],
    cta_eye="Start a project",
    cta_h2="Want to see your project <em>in render?</em>",
    cta_p="Send your drawings or your concept. We respond within two business days with a feasibility read, a render scope, and a tested quote.",
    cta_btn_text="Request a Quote",
    cta_btn_href="../contact.html",
    cta_bg="../projects/cta-vancouverhouse-living-dining.jpg",
)

# ─── BLOG ────────────────────────────────────────────────────────────────────

add(
    out="blog/index.html",
    prefix="../",
    title="Blog · Radius Architectural Millwork",
    desc="Notes from the shop floor. Joinery techniques, material studies, project progress, and the occasional rant about CNC.",
    canonical="https://radiuswood.com/blog/",
    crumbs=[("Home", "../"), ("Blog", None)],
    hero_img="../photos/indian-arm-study/indian-arm-woodlands-study-cedar-bookcase-pink-chair-sailboat.jpg",
    eyebrow="Blog",
    h1="Field notes <em>from the shop floor.</em>",
    copy_eye="What we write",
    copy_h2="Joinery, material, process. <em>Notes from the bench.</em>",
    copy_p="Field notes from the shop — written when we have something to say, not on a content calendar. Coming pieces include <strong>slip-matching at room scale</strong> (the logistics behind making a flitch run the room), <strong>the spring-back log book</strong> (twelve layers of veneer, custom jigs, and a humidity-keyed spreadsheet that took fifteen years to build), <strong>why anigre</strong> (a West African hardwood flitch-sourcing story), the <strong>AWMAC 2027 submission</strong> (Old Gravel Road, in progress on the bench), and <strong>why we still don't run a CNC</strong> (not nostalgia — a specific choice about details a machine can't make). Blog launches Spring 2026.",
    photos=[
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-mantel-carved-corbel-close-up.jpg", "Hand-carved corbel · cherry"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-stair-anigre-shelving-wall-led-step-lights-travertine-treads.jpg", "Anigre stair with LED-lit treads"),
        ("../photos/contemporary-walnut-estate/contemporary-walnut-estate-wine-cellar-walnut-racks-detail.jpg", "Vertical-rod walnut wine racking detail"),
        ("../photos/indian-river-the-point/indian-river-the-point-master-ensuite-rift-oak-vanity-freestanding-tub-green-tile.jpg", "Rift oak vanity · Indian River ensuite"),
    ],
    cta_eye="Notify me",
    cta_h2="Want a note when the blog goes live? <em>Drop us a line.</em>",
    cta_p="Blog launches Spring 2026. Send us an email and we'll put you on the list — joinery deep-dives, material studies, AWMAC submission notes as we go.",
    cta_btn_text="Notify Me",
    cta_btn_href="../contact.html",
    cta_bg="../photos/indian-arm-study/indian-arm-woodlands-study-cedar-bookcase-pink-chair-sailboat.jpg",
)

# ─── CONTACT ─────────────────────────────────────────────────────────────────

add(
    out="contact.html",
    prefix="",
    title="Contact · Radius Architectural Millwork · Burnaby BC",
    desc="604 444 1175 · rick@radiuswood.com · Unit 106 — 8575 Government Street, Burnaby BC. Shop visits by appointment. We respond within two business days.",
    canonical="https://radiuswood.com/contact/",
    crumbs=[("Home", "./"), ("Contact", None)],
    hero_img="projects/cta-vancouverhouse-living-dining.jpg",
    eyebrow="Contact",
    h1="Have a project? <em>Send us the set.</em>",
    copy_eye="Reach Us",
    copy_h2="Two business days, every time.",
    copy_p="<strong>Phone</strong> · <a href=\"tel:6044441175\">604 444 1175</a>. <strong>Email</strong> · <a href=\"mailto:rick@radiuswood.com\">rick@radiuswood.com</a>. <strong>The shop</strong> · Unit 106 — 8575 Government Street, Burnaby BC, V3N 4V1. <strong>Hours</strong> · Monday to Friday, 6:30am to 2:30pm. <strong>Shop visits by appointment</strong> — Friday afternoons usually work best. Bring drawings, bring questions; we'll show you the bench, the press, and the project on it. We respond to every inquiry within two business days with a feasibility read and a tested quote.",
    photos=[
        ("photos/indian-arm-study/indian-arm-woodlands-study-cedar-built-in-stone-fireplace-tight.jpg", "Cedar + stone · the bench's vocabulary"),
        ("photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-gallery-wine-bar-anigre-display-inuit-sculpture.jpg", "Gallery wine bar · anigre cabinetry"),
        ("photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-bocci-stairwell-dusk-exterior-view.jpg", "Bocci stairwell · Vancouver House"),
    ],
    cta_eye="Get in touch",
    cta_h2="Or just call. <em>We'll pick up.</em>",
    cta_p="The line goes to the office Monday through Friday during shop hours. After hours, leave a message — we'll call back the next morning.",
    cta_btn_text="Call 604 444 1175",
    cta_btn_href="tel:6044441175",
    cta_bg="projects/cta-vancouverhouse-living-dining.jpg",
)

# ─── WORK INDEX ──────────────────────────────────────────────────────────────

add(
    out="work/index.html",
    prefix="../",
    title="Our Work · Radius Architectural Millwork · Burnaby BC",
    desc="Selected residential estate millwork across Vancouver, the North Shore, and the Sea-to-Sky. From a Bjarke Ingels penthouse to slip-matched rift oak on Indian Arm.",
    canonical="https://radiuswood.com/our-work/",
    crumbs=[("Home", "../"), ("Our Work", None)],
    hero_img="../projects/indian-river-the-point.jpg",
    eyebrow="Our Work",
    h1="Selected residential <em>estate millwork.</em>",
    copy_eye="Selected Work",
    copy_h2="Eight projects from <em>the last decade on the bench.</em>",
    copy_p="Selected residential estate work across Vancouver, the North Shore, the Sea-to-Sky, and Whistler. Whole-house millwork packages, gallery wine bars, bent-laminated rotundas, diamond-bookmatched ceilings, slip-matched rift oak through public rooms. Featured projects below: <strong>Vancouverhouse BOP Penthouse</strong> (inside BIG's Vancouver House), <strong>Indian Arm Study</strong> (cedar-lined waterfront cabin), <strong>Indian River — The Point</strong> (slip-matched rift oak gable-end residence), <strong>West Vancouver Modern Luxury</strong> (banded cedar-slat ceiling), <strong>Waterfront Anigre Penthouse</strong> (diamond-bookmatched ceiling), <strong>Lion's Bay Residence</strong> (oceanfront painted millwork), <strong>Contemporary Walnut Estate</strong>, and <strong>Whitby Estates Walnut</strong>. AWMAC BC Gold winner <strong>Rosebery Estate</strong> also viewable.",
    photos=[
        ("../projects/vancouverhouse-bop-penthouse.jpg", "Vancouverhouse BOP Penthouse · Vancouver House · Downtown Vancouver", "vancouverhouse-bop-penthouse.html"),
        ("../projects/indian-arm-study.jpg", "Indian Arm Study · Indian Arm · Woodlands", "indian-arm-study.html"),
        ("../projects/indian-river-the-point.jpg", "Indian River — The Point · Indian Arm · The Point", "indian-river-the-point.html"),
        ("../projects/west-vancouver-modern-luxury.jpg", "West Vancouver Modern Luxury · West Vancouver · Coastal", "west-vancouver-modern-luxury.html"),
        ("../projects/waterfront-anigre-penthouse.jpg", "Waterfront Anigre Penthouse · Vancouver · Harbor", "waterfront-anigre-penthouse.html"),
        ("../projects/lions-bay.jpg", "Lion's Bay Residence · Lion's Bay · Howe Sound", "lions-bay.html"),
        ("../projects/contemporary-walnut-estate.jpg", "Contemporary Walnut Estate · Vancouver", "contemporary-walnut-estate.html"),
        ("../projects/whitby-estates-walnut.jpg", "Whitby Estates Walnut · West Vancouver · Maghsoud Residence", "whitby-estates-walnut.html"),
        ("https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/photos/archive/luxury-41.jpg", "Rosebery Estate · Vancouver West · AWMAC Gold 2011", "rosebery-estate.html"),
    ],
    cta_eye="Get in touch",
    cta_h2="Working on a project? <em>Send us the set.</em>",
    cta_p="Drawings, scope, timeline, or just a conversation. We respond within two business days with a feasibility read and a tested quote.",
    cta_btn_text="Request a Quote",
    cta_btn_href="../contact.html",
    cta_bg="../projects/cta-vancouverhouse-living-dining.jpg",
)

# ─── PROJECT PAGES ───────────────────────────────────────────────────────────

PROJECT_CTA = {
    "cta_eye": "Get in touch",
    "cta_h2": "Working on a project? <em>Send us the set.</em>",
    "cta_p": "Drawings, scope, timeline, or just a conversation. We respond within two business days with a feasibility read and a tested quote.",
    "cta_btn_text": "Request a Quote",
    "cta_btn_href": "../contact.html",
    "cta_bg": "../projects/cta-vancouverhouse-living-dining.jpg",
}


def project(slug, title_html, title_text, hero_img_proj, eyebrow_loc, copy_h2, copy_p, photos, schema_locality, schema_year=None, schema_image=None, schema_desc=None):
    add(
        out=f"work/{slug}.html",
        prefix="../",
        title=f"{title_text} · Radius Architectural Millwork",
        desc=copy_p.replace("<strong>", "").replace("</strong>", "").replace("<em>", "").replace("</em>", "")[:200],
        canonical=f"https://radiuswood.com/our-work/{slug}/",
        crumbs=[("Home", "../"), ("Our Work", "./"), (title_text, None)],
        hero_img=f"../projects/{hero_img_proj}.jpg",
        eyebrow=f"Our Work · {eyebrow_loc}",
        h1=title_html,
        copy_eye="The Project",
        copy_h2=copy_h2,
        copy_p=copy_p,
        photos=photos,
        schema_extra={
            "type": "CreativeWork",
            "name": title_text,
            "locality": schema_locality,
            "year": schema_year,
            "image": schema_image,
            "desc": schema_desc or copy_p[:300],
        },
        **PROJECT_CTA,
    )


# Vancouverhouse BOP
project(
    "vancouverhouse-bop-penthouse",
    "Vancouverhouse <em>BOP Penthouse</em>",
    "Vancouverhouse BOP Penthouse",
    "vancouverhouse-bop-penthouse",
    "Vancouver House",
    "Bookmatched walnut, <em>inside Bjarke Ingels' tower.</em>",
    "A penthouse inside <strong>Bjarke Ingels Group's Vancouver House</strong> — the twisting triangle tower at the south edge of downtown Vancouver. The interior had to live up to the shell without competing with it. The brief landed on a single material gesture: <strong>American walnut, bookmatched, run as both ceiling slats and full-height cabinetry</strong>, with black marble as the counter-note. The standout is a three-storey <strong>Bocci pendant installation</strong> in the central stairwell, visible from inside through a glass wall and from the street at dusk. The master ensuite carries the move further with a <strong>curved walnut slat wall</strong> wrapping the freestanding tub — each slat cut as its own ribbon and set against a bent-laminated spine on a steel substructure.",
    [
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-living-room-atrium-garden-walnut-slat-ceiling.jpg", "Living room · atrium garden · walnut slat ceiling"),
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-kitchen-walnut-marble-backsplash-island.jpg", "Kitchen · bookmatched walnut · black marble"),
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-bocci-stairwell-dusk-exterior-view.jpg", "Bocci stairwell · dusk exterior view"),
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-master-bath-freestanding-tub-curved-walnut-slat-wall.jpg", "Master ensuite · curved walnut slat wall"),
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-walnut-slat-corridor-bocci-stair-view.jpg", "Walnut slat corridor · view to Bocci stair"),
        ("../photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-powder-bath-trough-sink-mirror-wall.jpg", "Powder bath · stone trough sink · mirror wall"),
    ],
    "Vancouver", "2020",
    schema_image="https://radiuswood.com/our-work/photos/vancouverhouse-bop-penthouse/vancouverhouse-bop-penthouse-living-room-atrium-garden-walnut-slat-ceiling.jpg",
)

# Indian Arm Study
project(
    "indian-arm-study",
    "Indian Arm <em>Study</em>",
    "Indian Arm Study",
    "indian-arm-study",
    "Indian Arm · Woodlands",
    "Cedar, stone, <em>and a single curved desk.</em>",
    "A writer's cabin on Indian Arm. <strong>Cedar tongue-and-groove</strong> for the ceiling, walls, and the full-height built-in bookcase that lines one side of the room. A wall of <strong>locally collected stone</strong> as the counter-note — dry-stacked, no mortar joint visible from the room side. Where the cedar meets the stone, the joint is scribed to the rock — a hairline reveal, no caulk, no margin. A <strong>curved-edge desk slab</strong> cantilevers off the cedar wall with no visible support; the structure runs back into the wall. A globe-pendant cluster on a red-cable harness drops from the cedar ceiling. The leather Maralunga is the only piece of furniture in the room that isn't built in.",
    [
        ("../photos/indian-arm-study/indian-arm-woodlands-study-living-room-wide-stone-wall.jpg", "Cedar + stone wall with globe pendant cluster"),
        ("../photos/indian-arm-study/indian-arm-woodlands-study-cedar-bookcase-pink-chair-sailboat.jpg", "Cedar built-in bookcase with sailboat model"),
        ("../photos/indian-arm-study/indian-arm-woodlands-study-cedar-desk-curved-edge-ocean-view.jpg", "Curved-edge cedar desk with ocean view"),
        ("../photos/indian-arm-study/indian-arm-woodlands-study-leather-chair-globe-pendants-vertical.jpg", "Leather Maralunga with globe pendants"),
        ("../photos/indian-arm-study/indian-arm-woodlands-study-living-room-wide-cedar-ceiling.jpg", "Living room wide with cedar ceiling"),
        ("../photos/indian-arm-study/indian-arm-woodlands-study-exterior-cedar-cabin-dusk-trees.jpg", "Exterior cedar cabin at dusk"),
    ],
    "North Vancouver",
    schema_image="https://radiuswood.com/our-work/photos/indian-arm-study/indian-arm-woodlands-study-living-room-wide-stone-wall.jpg",
)

# Indian River The Point
project(
    "indian-river-the-point",
    "Indian River — <em>The Point</em>",
    "Indian River — The Point",
    "indian-river-the-point",
    "Indian Arm · The Point",
    "Slip-matched rift oak <em>through a gable-end residence.</em>",
    "A modern gable-end residence on Indian Arm where the architectural move is a single tall window framing the harbor — and the millwork has to hold its own next to it. <strong>Slip-matched rift white oak</strong> through the public rooms, a <strong>river-rock chimney column</strong> rising past the slats, <strong>black wenge</strong> as the dark counter-note in the dining wall, and a tongue-and-groove stair worked in the same oak as the cabinetry so it reads as one continuous material gesture. The flitch is sequenced on the floor in shop order before it sees a press; the figure lands at the door breaks and the appliance returns. A painted moss-green island with a honed soapstone top is the counterpoint to all the oak. Photography by Andrew Latreille.",
    [
        ("../photos/indian-river-the-point/indian-river-the-point-living-room-gable-end-harbor-view-bocci-pendants-media-wall.jpg", "Living room · gable-end glazing · Bocci pendants"),
        ("../photos/indian-river-the-point/indian-river-the-point-kitchen-white-oak-slat-wall-river-rock-fireplace-column.jpg", "Kitchen · white oak slats · river-rock chimney"),
        ("../photos/indian-river-the-point/indian-river-the-point-dining-black-wenge-cabinets-pendant-trio-leather-chairs.jpg", "Dining · black wenge buffet wall"),
        ("../photos/indian-river-the-point/indian-river-the-point-kitchen-white-oak-pantry-open-moss-green-island.jpg", "Kitchen pantry open · moss-green island"),
        ("../photos/indian-river-the-point/indian-river-the-point-master-bedroom-white-oak-wardrobe-wall.jpg", "Master bedroom · white oak wardrobe wall"),
        ("../photos/indian-river-the-point/indian-river-the-point-master-ensuite-rift-oak-vanity-freestanding-tub-green-tile.jpg", "Master ensuite · rift oak vanity · sage tile"),
        ("../photos/indian-river-the-point/indian-river-the-point-white-oak-stair-tongue-and-groove.jpg", "Tongue-and-groove rift oak stair"),
    ],
    "North Vancouver", "2025",
    schema_image="https://radiuswood.com/our-work/photos/indian-river-the-point/indian-river-the-point-living-room-gable-end-harbor-view-bocci-pendants-media-wall.jpg",
)

# West Vancouver Modern Luxury
project(
    "west-vancouver-modern-luxury",
    "West Vancouver <em>Modern Luxury</em>",
    "West Vancouver Modern Luxury",
    "west-vancouver-modern-luxury",
    "West Vancouver · Coastal",
    "Banded cedar-slat ceilings <em>over an ocean-view coffee bar.</em>",
    "A modern coastal residence with the kind of view the architecture is built to frame. <strong>Cedar-slat ceiling bands</strong> with integrated downlight strips run across the main public rooms — a ceiling that's also the lighting plan. Each band runs the full length of the room; the joint where the band breaks is hidden in shadow. Glass curtain walls slide open to a cantilevered ocean-view deck. The kitchen and coffee bar share the same vocabulary: <strong>saffron-painted upper cabinets</strong>, grey textured base cabinets, AEG appliances. The interior's counter-note is a pair of <strong>antique carved double doors</strong> sourced from an estate sale and re-hung as the entry to a wine cellar lined with spiral racking — patinated old wood against the clean modern shell.",
    [
        ("../photos/west-vancouver-modern-luxury/west-vancouver-modern-luxury-coffee-bar-ceiling-banded-lights-fireplace-wide.jpg", "Coffee bar · banded cedar-slat ceiling lights"),
        ("../photos/west-vancouver-modern-luxury/west-vancouver-modern-luxury-coffee-bar-saffron-uppers-grey-textured.jpg", "Coffee bar · saffron uppers · AEG oven"),
        ("../photos/west-vancouver-modern-luxury/west-vancouver-modern-luxury-wine-cellar-antique-carved-doors-interior-view.jpg", "Wine cellar entry · antique carved doors"),
        ("../photos/west-vancouver-modern-luxury/west-vancouver-modern-luxury-curved-stair-concrete-wall-cherry-treads.jpg", "Curved stair · concrete wall · cherry treads"),
        ("../photos/west-vancouver-modern-luxury/west-vancouver-modern-luxury-exterior-deck-pool-ocean-view-cedar-railing.jpg", "Exterior · deck · pool · ocean view"),
        ("../photos/west-vancouver-modern-luxury/west-vancouver-modern-luxury-kitchen-saffron-storage-wall-light-wood.jpg", "Kitchen · saffron storage wall · light wood"),
    ],
    "West Vancouver",
    schema_image="https://radiuswood.com/our-work/photos/west-vancouver-modern-luxury/west-vancouver-modern-luxury-coffee-bar-ceiling-banded-lights-fireplace-wide.jpg",
)

# Waterfront Anigre Penthouse
project(
    "waterfront-anigre-penthouse",
    "Waterfront <em>Anigre Penthouse</em>",
    "Waterfront Anigre Penthouse",
    "waterfront-anigre-penthouse",
    "Vancouver · Harbor",
    "Diamond-bookmatched anigre <em>over a gallery wine bar.</em>",
    "A harbor-front penthouse where the ceiling does the heavy lifting. <strong>Diamond-bookmatched anigre panels</strong> over a steel armature, sequenced so that every diamond rotates the flitch ninety degrees — the figure reads as one woven plane from any vantage. Beneath it: a Bocci pendant cluster, a granite-topped kitchen island, and a gallery wine bar built around the owner's collection of Inuit soapstone sculpture. <strong>Lit anigre display niches</strong> step across the back wall behind tempered glass; the bottle racks pull out as a single carriage. An <strong>art-deco stair</strong> at the entry — travertine treads, LED-lit risers, open anigre shelving wall on the inside line — reads as a private museum the moment you step in. Photography by Hempenstall.",
    [
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-living-dining-diamond-ceiling-wide-fireplace-wine-bar-dusk.jpg", "Living-dining · diamond ceiling · fireplace · wine bar · dusk"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-kitchen-bocci-pendants-granite-island-anigre-cabinetry.jpg", "Kitchen · Bocci pendants · granite island"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-gallery-wine-bar-anigre-display-inuit-sculpture.jpg", "Gallery wine bar · Inuit sculpture display"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-stair-anigre-shelving-wall-led-step-lights-travertine-treads.jpg", "Art-deco stair · anigre shelving · LED step lights"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-media-tv-fireplace-diamond-ceiling-inuit-gallery-wall.jpg", "Media room · diamond ceiling · Inuit gallery wall"),
        ("../photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-master-ensuite-travertine-vanity-tub-shower-wide.jpg", "Master ensuite · travertine vanity · tub"),
    ],
    "Vancouver",
    schema_image="https://radiuswood.com/our-work/photos/waterfront-anigre-penthouse/waterfront-anigre-penthouse-living-dining-diamond-ceiling-wide-fireplace-wine-bar-dusk.jpg",
)

# Lion's Bay
project(
    "lions-bay",
    "Lion's Bay <em>Residence</em>",
    "Lion's Bay Residence",
    "lions-bay",
    "Lion's Bay · Howe Sound",
    "Antique-white painted millwork <em>on Howe Sound.</em>",
    "A traditional oceanfront residence on Howe Sound with a view of the islands you don't have to be told to look at. <strong>Antique-white painted millwork</strong> throughout — the cabinetry, the panelling, the corbel-carrying mantels, the beadboard inserts. A red Viking range as the kitchen's single saturated note. The architectural move is a <strong>curved dining nook</strong> that wraps the corner of the public room, framing the harbour through a bay window. Cabinetry is hard maple, painted at the shop and finished with a low-VOC conversion varnish that holds up to coastal humidity. The glaze is hand-wiped in a single application — the figure follows the carved profiles into the corners where painters don't always go. Hand-carved corbels sit under every mantel.",
    [
        ("../photos/lions-bay/lions-bay-residence-living-room-curved-dining-nook-ocean-view.jpg", "Curved dining nook · bay window · ocean view"),
        ("../photos/lions-bay/lions-bay-residence-kitchen-wide-antique-white-island-viking-range.jpg", "Kitchen · antique-white island · Viking range"),
        ("../photos/lions-bay/lions-bay-residence-kitchen-viking-range-hood-tile-mural.jpg", "Viking range · carved corbels · tile mural"),
        ("../photos/lions-bay/lions-bay-residence-painted-corbel-carved-detail.jpg", "Painted carved corbel close-up"),
        ("../photos/lions-bay/lions-bay-residence-kitchen-arched-opening-living-room-wide.jpg", "Kitchen · arched opening · living room"),
        ("../photos/lions-bay/lions-bay-residence-glazed-walnut-bar-console-birch-art.jpg", "Glazed walnut bar console · birch art"),
    ],
    "Lion's Bay",
    schema_image="https://radiuswood.com/our-work/photos/lions-bay/lions-bay-residence-living-room-curved-dining-nook-ocean-view.jpg",
)

# Contemporary Walnut Estate
project(
    "contemporary-walnut-estate",
    "Contemporary <em>Walnut Estate</em>",
    "Contemporary Walnut Estate",
    "contemporary-walnut-estate",
    "Vancouver",
    "Slip-matched walnut <em>through every room.</em>",
    "A Vancouver estate where the brief was a single material gesture: <strong>slip-matched American walnut, run through every public and private room</strong>. The dining feature wall lights a fireplace into the walnut grain. The wine cellar reads as a single sculpted volume of walnut and bottles — <strong>vertical-rod racking</strong> tensioned between the floor and ceiling, with cork-faced bottle cradles, glass-fronted to the hallway so the racks become the wall. The master suite headboard wall continues the same flitch as the public-room cabinetry. His-and-hers walk-in closets carry the walnut through the dressing room, into custom walnut dressers and shoe walls. The house is contemporary in proportion — high ceilings, clean returns, no applied moulding — but rich in material.",
    [
        ("../photos/contemporary-walnut-estate/contemporary-walnut-estate-dining-room-wide-fireplace-wine-wall.jpg", "Dining · walnut feature wall · fireplace · wine wall"),
        ("../photos/contemporary-walnut-estate/contemporary-walnut-estate-wine-cellar-walnut-rack-perspective.jpg", "Wine cellar · vertical-rod walnut racking"),
        ("../photos/contemporary-walnut-estate/contemporary-walnut-estate-master-bedroom-headboard-wall-wide.jpg", "Master bedroom · walnut headboard wall"),
        ("../photos/contemporary-walnut-estate/contemporary-walnut-estate-walnut-fireplace-wall-detail.jpg", "Walnut fireplace wall · vertical detail"),
        ("../photos/contemporary-walnut-estate/contemporary-walnut-estate-wine-cellar-walnut-racks-detail.jpg", "Vertical-rod wine racks · close-up"),
        ("../photos/contemporary-walnut-estate/contemporary-walnut-estate-media-room-walnut-cabinetry-screen.jpg", "Media room · walnut credenza"),
    ],
    "Vancouver",
    schema_image="https://radiuswood.com/our-work/photos/contemporary-walnut-estate/contemporary-walnut-estate-dining-room-wide-fireplace-wine-wall.jpg",
)

# Whitby Estates Walnut
project(
    "whitby-estates-walnut",
    "Whitby <em>Estates Walnut</em>",
    "Whitby Estates Walnut",
    "whitby-estates-walnut",
    "West Vancouver · Maghsoud Residence",
    "Cherry-walnut panelling <em>with hand-carved corbels.</em>",
    "The Maghsoud Residence at Whitby Estates — a traditional Persian-influenced estate where the millwork vocabulary is <strong>cherry-walnut panelling, coffered ceilings, and hand-carved corbels</strong> over every mantel and counter overhang. The whole-house package: media room, library, butler's pantry, his-and-hers walk-ins, a foyer rotunda, a wrought-iron stair, and an elevator cab lined in matching cherry. The <strong>mahogany double doors</strong> at the entry carry crotch-mahogany inlay panels — the figured-grain section of the log, hand-cut and book-matched into the stile-and-rail frame. Hand-carved corbels are turned and chiseled at the bench, then finished to match the cherry. The crown mouldings are dentil-pattern. Every detail finished by hand.",
    [
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-media-room-corner-wide-built-ins-double-doors.jpg", "Media room · coffered ceiling · mahogany doors"),
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-mahogany-double-doors-open-entry-perspective.jpg", "Mahogany double doors · open entry"),
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-mantel-carved-corbel-close-up.jpg", "Hand-carved cherry corbel"),
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-media-room-wide-coffered-tv-fireplace-built-ins.jpg", "Media room wide · TV over fireplace"),
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-cherry-panel-wall-bookmatched-detail.jpg", "Bookmatched cherry panel · vertical detail"),
        ("../photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-walnut-pantry-glass-cabinets-arched-niche.jpg", "Walnut pantry · glass cabinets · arched niche"),
    ],
    "West Vancouver",
    schema_image="https://radiuswood.com/our-work/photos/whitby-estates-walnut/whitby-estates-walnut-maghsoud-residence-media-room-corner-wide-built-ins-double-doors.jpg",
)

# Rosebery Estate (AWMAC Gold 2011 — legacy photos)
project(
    "rosebery-estate",
    "Rosebery <em>Estate</em>",
    "Rosebery Estate",
    "vancouverhouse-bop-penthouse",  # placeholder, overridden below
    "Vancouver West · AWMAC Gold 2011",
    "Bent-laminated alder <em>through a private Vancouver residence.</em>",
    "A private Vancouver residence with <strong>Lamoureux Architects</strong>. The brief: bent-laminated structural radii throughout the public rooms, slip-matched alder panelling room-to-room, walnut furniture detailing, and the kind of coffered ceiling work that asks a millwork shop to be both engineer and craftsman. Eighteen months on the bench. Fifteen craftspeople full-time. $1.5M millwork scope. The technical challenge was laminated curves — twelve layers of alder veneer per radius, custom jigs cut for every radius, spring-back logged per species and humidity. Every curve test-fitted dry before glue-up; curves paired to cancel the spring before bonding the final field. <strong>AWMAC BC Gold for Best Quality and Best Service, 2011.</strong>",
    [
        ("https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/photos/archive/luxury-41.jpg", "Curved alder rotunda · bent-laminated balustrade"),
        ("https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/photos/archive/luxury-1.jpg", "Two-storey curved alder foyer · grand stair"),
        ("https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/photos/archive/luxury-22.jpg", "Walnut display case · raised-panel base"),
        ("https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/photos/joinery/dovetail-pin-tail-maple-close.jpg", "Pin-and-tail dovetail joinery detail"),
        ("https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/photos/joinery/ebonised-reveal-line-corner.jpg", "Ebonised inlay carrying around a corner"),
        ("https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/photos/material/sequence-matched-rift-oak-doors.jpg", "Sequence-matched rift oak doors"),
    ],
    "Vancouver", "2011",
    schema_image="https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/photos/archive/luxury-41.jpg",
)
# Override Rosebery's hero image to use the archive luxury-41
PAGES[-1]["hero_img"] = "https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/photos/archive/luxury-41.jpg"


# ────────────────────────────────────────────────────────────────────────────
# Template
# ────────────────────────────────────────────────────────────────────────────

def render_breadcrumb(crumbs):
    parts = []
    for i, (label, href) in enumerate(crumbs):
        if i > 0:
            parts.append('<span class="sep">/</span>')
        if href:
            parts.append(f'<a href="{href}">{label}</a>')
        else:
            parts.append(f'<span>{label}</span>')
    return "\n      ".join(parts)


def render_nav(prefix):
    return f"""<nav class="site" id="nav">
  <a href="{prefix}" class="brand-lockup" aria-label="Radius Architectural Millwork — Home">
    <img class="logo" src="https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/brand/radius-logo.png" alt="Radius Architectural Millwork">
  </a>
  <div class="links">
    <div class="nav-item">
      <a href="{prefix}about/">About <span class="caret">▾</span></a>
      <div class="dropdown">
        <a href="{prefix}about/company.html">Company</a>
        <a href="{prefix}about/our-vision.html">Our Vision</a>
        <a href="{prefix}about/partners.html">Partners</a>
      </div>
    </div>
    <div class="nav-item">
      <a href="{prefix}services/">Services <span class="caret">▾</span></a>
      <div class="dropdown">
        <a href="{prefix}services/architectural-millwork.html">Architectural Millwork</a>
        <a href="{prefix}services/3d-renderings.html">3D Renderings</a>
      </div>
    </div>
    <a href="{prefix}work/">Our Work</a>
    <a href="{prefix}blog/">Blog</a>
    <a href="{prefix}contact.html">Contact</a>
    <a href="{prefix}contact.html" class="cta">Get In Touch</a>
  </div>
</nav>"""


def render_footer(prefix):
    return f"""<footer class="site">
  <div class="footer-inner">
    <div class="footer-grid">
      <div class="footer-col footer-brand">
        <img src="https://mattanthonyphoto.github.io/matt-proposals/radiuswood/posts/brand/radius-logo.png" alt="Radius Architectural Millwork">
        <p>A Master Joiner-led custom millwork shop in Burnaby, BC. Twenty-five years on the same bench.</p>
        <div class="legal">Since 2002 · Burnaby BC<br>AWMAC Gold 2011 · 5× Best of Houzz<br>Licence BUS05-01768</div>
      </div>
      <div class="footer-col">
        <h4>About</h4>
        <ul>
          <li><a href="{prefix}about/company.html">Company</a></li>
          <li><a href="{prefix}about/our-vision.html">Our Vision</a></li>
          <li><a href="{prefix}about/partners.html">Partners</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Services</h4>
        <ul>
          <li><a href="{prefix}services/architectural-millwork.html">Architectural Millwork</a></li>
          <li><a href="{prefix}services/3d-renderings.html">3D Renderings</a></li>
          <li><a href="{prefix}work/">Our Work</a></li>
          <li><a href="{prefix}blog/">Blog</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Service Area</h4>
        <ul>
          <li>Vancouver</li>
          <li>Burnaby</li>
          <li>West Vancouver</li>
          <li>North Vancouver</li>
          <li>Whistler · Squamish</li>
        </ul>
      </div>
      <div class="footer-col footer-contact">
        <h4>Contact</h4>
        <div class="row"><span class="label">Phone</span><div class="val"><a href="tel:6044441175">604 444 1175</a></div></div>
        <div class="row"><span class="label">Email</span><div class="val"><a href="mailto:rick@radiuswood.com">rick@radiuswood.com</a></div></div>
        <div class="row"><span class="label">Shop</span><div class="val">Unit 106 – 8575<br>Government St, Burnaby</div></div>
      </div>
    </div>
    <div class="footer-bottom">
      <div>© 2026 Radius Architectural Millwork Ltd.</div>
      <div class="socials">
        <a href="https://instagram.com/radiusmillwork" target="_blank" rel="noopener">Instagram</a>
        <a href="https://linkedin.com/company/radius-architectural-millwork" target="_blank" rel="noopener">LinkedIn</a>
        <a href="#" target="_blank" rel="noopener">Houzz</a>
      </div>
    </div>
  </div>
</footer>"""


def render_photos(photos):
    """photos: list of (src, caption) OR (src, caption, href) tuples."""
    out = []
    for p in photos:
        if len(p) == 3:
            src, cap, href = p
            out.append(f'<a href="{href}"><figure><img loading="lazy" src="{src}" alt="{cap}"><figcaption>{cap}</figcaption></figure></a>')
        else:
            src, cap = p
            out.append(f'<figure><img loading="lazy" src="{src}" alt="{cap}"><figcaption>{cap}</figcaption></figure>')
    return "\n  ".join(out)


def render_schema(page):
    extra = page.get("schema_extra")
    if not extra:
        return ""
    locality = extra["locality"]
    year_line = f',\n  "dateCreated": "{extra["year"]}"' if extra.get("year") else ""
    desc = extra["desc"]
    image = extra["image"]
    name = extra["name"]
    return f"""<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "CreativeWork",
  "name": "{name}",
  "creator": {{"@type": "Organization", "name": "Radius Architectural Millwork Ltd"}},
  "locationCreated": {{"@type": "Place", "address": {{"@type": "PostalAddress", "addressLocality": "{locality}", "addressRegion": "BC", "addressCountry": "CA"}}}}{year_line},
  "image": "{image}",
  "description": "{desc}"
}}
</script>"""


def render_page(page):
    prefix = page["prefix"]
    crumbs_html = render_breadcrumb(page["crumbs"])
    schema_block = render_schema(page)
    photos_html = render_photos(page["photos"])
    css_href = f'{prefix}css/site.css' if prefix else 'css/site.css'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{page["title"]}</title>
<meta name="description" content="{page["desc"]}">
<link rel="canonical" href="{page["canonical"]}">
{schema_block}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@1,300;1,400;1,500&family=Roboto:wght@300;400;500&family=Varta:wght@300;400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{css_href}">
</head>
<body>

{render_nav(prefix)}

<section class="hero-banner">
  <img src="{page["hero_img"]}" alt="{page["title"]} — hero">
  <div class="breadcrumb">
      {crumbs_html}
  </div>
  <div class="overlay">
    <span class="eyebrow">{page["eyebrow"]}</span>
    <h1>{page["h1"]}</h1>
  </div>
</section>

<section class="page-copy">
  <span class="eyebrow">{page["copy_eye"]}</span>
  <h2>{page["copy_h2"]}</h2>
  <p>{page["copy_p"]}</p>
</section>

<section class="photo-stack">
  {photos_html}
</section>

<section class="cta-band cta-image" style="--cta-bg: url('{page["cta_bg"]}');">
  <span class="eyebrow">{page["cta_eye"]}</span>
  <h2>{page["cta_h2"]}</h2>
  <p>{page["cta_p"]}</p>
  <a href="{page["cta_btn_href"]}" class="cta-btn">{page["cta_btn_text"]}</a>
</section>

{render_footer(prefix)}

<script>
  const nav = document.getElementById('nav');
  if (nav) {{
    document.addEventListener('scroll', () => {{
      nav.classList.toggle('scrolled', window.scrollY > 70);
    }}, {{ passive: true }});
  }}
</script>

</body>
</html>
"""


def main():
    for page in PAGES:
        out_path = HOME / page["out"]
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(render_page(page))
        print(f"OK {page['out']}")


if __name__ == "__main__":
    main()
